config/routes.rb
Rails.application.routes.draw do



  resources :corsairs

  root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
  validates :age, :inclusion => {:in => 15..120}
  validates :slack_handle, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates :github_handle, format: { with: /\A[a-zA-Z0-9]+\Z/ }




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController
  def index
    @corsairs=Corsair.all
  end

  def show
    @corsair=Corsair.find(params[:id])
  end

  def edit
    @corsair=Corsair.find(params[:id])
  end

  def update
    @corsair=Corsair.find(params[:id])
    @corsair.update(corsair_params)
    if @corsair.save
      flash[:success] = "Modification réussie !"
      redirect_to corsairs_path
    else
      render 'update'
    end
  end

  def delete

  end

  def destroy
    @corsair=Corsair.find(params[:id])
    @corsair.destroy
    redirect_to corsairs_path
  end

  def new
    @corsair=Corsair.new
  end

  def create
  @corsair = Corsair.new(corsair_params)
  if @corsair.save
    flash[:success] = "Inscription réussie !"
    redirect_to corsairs_path
  else
    render 'new'
  end
end

  private

  def corsair_params
    params.require(:corsair).permit(:first_name, :age, :slack_handle, :github_handle, :bio, :likeness)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Corsair.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def new

  end

  def show

  end

  def edit

  end

  def index
    @corsaires = corsaire.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/delete.html.erb
<h1>Corsairs#delete</h1>
<p>Find me in app/views/corsairs/delete.html.erb</p>

app/views/corsairs/edit.html.erb
<h2>Editer le profil</h2>

<%= form_for @corsair do |f| %>

    <div class="group-form">
      <label>Nom du corsaire</label>
      <%=  f.text_field :first_name,
                        :maxlength => 20,
                        :required => true,
                        class: "form-control" %>
    </div>

    <div class="group-form">
      <label>Age</label>
      <%=  f.text_field :age,
                        :required => true,
                        class: "form-control"
      %>
    </div>

    <div class="group-form">
      <label>Slack</label>
      <%=  f.text_field :slack_handle,
                        class: "form-control"
      %>
    </div>

    <div class="group-form">
      <label>Github</label>
      <%=  f.text_field :github_handle,
                        class: "form-control"
      %>
    </div>

    <div class="group-form">
      <label>Bio</label>
      <%=  f.text_field :bio,
                        class: "form-control"
      %>
    </div>

    <div class="group-form">
      <p><label>Nourriture</label></p>
      <%= f.radio_button :likeness, 'kebab' %>
      <%= f.label :likeness, 'Kebab', :value => 'Kebab' %>
      <%= f.radio_button :likeness, 'hummus' %>
      <%= f.label :likeness, 'Hummus', :value => 'Hummus' %>
    </div>



    <div class="group-form">
      <button type="submit">Enregistrer la modification</button>
    </div>

    <div class="group-form">
      <a href="<%= corsair_path %>" class="btn btn-danger" data-method="DELETE">Supprimer</a>
    </div>
<% end %>

app/views/corsairs/index.html.erb
<h2>Liste des corsairs</h2>

<% @corsairs.each do |corsair| %>

    <p><%= corsair.first_name %></p>
    <p><%= corsair.age %></p>



    <p><%= link_to "Voir le profil", corsair_path(corsair), method: "get", class: "btn btn-lg btn-primary" %></p>

<% end %>

<p><%= link_to "Créer un nouveau profil", new_corsair_path, method: "get", class: "btn btn-lg btn-success" %></p>

app/views/corsairs/new.html.erb
<h2>Créer un profil</h2>

<%= form_for @corsair do |f| %>

    <div class="group-form">
      <label>Nom du corsaire</label>
      <%=  f.text_field :first_name,
                        :maxlength => 20,
                        class: "form-control" %>
    </div>

    <div class="group-form">
      <label>Age</label>
      <%=  f.text_field :age,
                        class: "form-control" %>
    </div>

    <div class="group-form">
      <label>Slack account</label>
      <%=  f.text_field :slack_handle,
                        class: "form-control" %>
    </div>

    <div class="group-form">
      <label>Github account</label>
      <%=  f.text_field :github_handle,
                        class: "form-control" %>
    </div>

    <div class="group-form">
      <label>Bio</label>
      <%=  f.text_field :bio,
                        class: "form-control" %>
    </div>

    <div class="group-form">
      <p><label>Nourriture</label></p>
      <%= f.radio_button :likeness, 'kebab' %>
      <%= f.label :likeness, 'Kebab', :value => 'Kebab' %>
      <%= f.radio_button :likeness, 'hummus' %>
      <%= f.label :likeness, 'Hummus', :value => 'Hummus' %>
    </div>

    <div class="group-form">
      <button type="submit">Enregistrer le profil</button>
    </div>
<% end %>

app/views/corsairs/show.html.erb
<h2>Profil du corsair</h2>
<h4>Nom</h4>
<p><%= @corsair.first_name %></p>
<h4>Age</h4>
<p><%= @corsair.age %></p>
<h4>Compte Slack</h4>
<% if @corsair.slack_handle != nil %>
    <p><%=@corsair.slack_handle%></p>
<% else %>
    <p><%=@corsair.first_name%> n'a pas encore renseigné son pseudo Slack !</p>
<% end %>
<h4>Compte Github</h4>
<% if @corsair.slack_handle != nil %>
    <p><%=@corsair.github_handle%></p>
<% else %>
    <p><%=@corsair.first_name%> n'a pas encore renseigné son pseudo Github !</p>
<% end %>
<h4>Biographie</h4>
<% if @corsair.slack_handle != nil %>
    <p><%=@corsair.bio%></p>
<% else %>
    <p><%=@corsair.first_name%> n'a pas encore renseigné sa biographie !</p>
<% end %>
<h4>Nourriture</h4>
<% if @corsair.likeness != nil %>
    <p><%=@corsair.likeness %></p>
<% else %>
    <p><%=@corsair.likeness%> n'a pas encore renseigné kebab ou hummus !</p>
<% end %>



<%= link_to "Modifier le profil", edit_corsair_path, method: "get", class: "btn btn-lg btn-warning" %>

<%= link_to "Retour à la liste", corsairs_path, method: "get", class: "btn btn-lg btn-primary" %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path, method: "get" %></li>
        <li><%= link_to "Index des corsaires", corsairs_path, method: "get" %></li>
        <li><%= link_to "Nouveau corsaire", new_corsair_path, method: "get" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpCorsaires</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-0.8.1.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h2>Liste des corsairs</h2>

<% @corsairs.each do |corsair| %>

  <p><%= corsair.first_name %></p>
    <p><%= corsair.age %></p>

    <%= link_to "Voir le profil", corsaire_path, method: "get" %>


<% end %>

app/views/static_pages/edit.html.erb
<h1>StaticPages#edit</h1>
<p>Find me in app/views/static_pages/edit.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Hello jeune pirate!</h1>
  <h3>
    Ici tu pourras retrouver tous les corsaires ! 
  </h3>
  <%= link_to "Crée un profil corsaire !", new_corsair_path, class: "btn btn-lg btn-primary" %>
</div>